version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - c:/Users/roger/git/nodejs-course/25-backend-async/dbdata:/data/db
    command: [--auth]
