version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - c:/Users/roger/git/nodejs-course/10-sql/dbdata:/var/lib/mysql